---
- name: install and config apache2
  hosts: serverweb
  become: true
  tasks:
   - name: apache2
     apt:
      name: apache2
      state: present
   - name: blablabla
     hosts: serverweb
     become: true
     tasks:
      - name: apache2
        apt: 
         name: apache2
         state: present
      - name: creation index
        copy:
          content: <html>
           <head>
            <title>Bienvenue chez jerome</title>
           </head>
          <body>
           <h1> blblalavlblblbl</h1>
          </body>
         </html>
       dest: /var/www/html/index.html
     - name: demarrage service
       service:
        name: apache2
        state: started
        
